"""Added photos table and relation to house

Revision ID: c1ac343ac87e
Revises: 8217fc708678
Create Date: 2022-07-09 12:41:51.508153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1ac343ac87e'
down_revision = '8217fc708678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('PNG', 'JPG', 'JPEG', name='datatypes'), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('file_name')
    )
    op.add_column('photo', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('photo', sa.Column('file_type', sa.Enum('PNG', 'JPG', 'JPEG', name='phototypes'), nullable=False))
    op.add_column('photo', sa.Column('file_id', sa.String(), nullable=False))
    op.add_column('photo', sa.Column('url', sa.String(), nullable=False))
    op.add_column('photo', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('photo', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'photo', ['filename'])
    op.create_unique_constraint(None, 'photo', ['file_id'])
    op.drop_column('photo', 'date')
    op.drop_column('photo', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('photo', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'photo', type_='unique')
    op.drop_constraint(None, 'photo', type_='unique')
    op.drop_column('photo', 'time_updated')
    op.drop_column('photo', 'time_created')
    op.drop_column('photo', 'url')
    op.drop_column('photo', 'file_id')
    op.drop_column('photo', 'file_type')
    op.drop_column('photo', 'filename')
    op.drop_table('object')
    # ### end Alembic commands ###
